import { formatSearchResponse } from '../../src/utils/formatSearchResponse';
import { MORE_INFO_MOCK_DATA, MOCK_VOCABULARY_DATA } from '../../src/services/handlers/mocks/more-info-response';
import { naturalTabStaticData } from '../../src/utils/constants';

describe('Format the search response', () => {
  it('should format the search response correctly', async () => {
    const result = await formatSearchResponse(MORE_INFO_MOCK_DATA, MOCK_VOCABULARY_DATA);
    const expectedResponse = {
      '0': {
        tab: 'governance',
        role: 'pointOfContact',
        organization_name: '',
        individual_name: 'Jonathan Smith',
        position_name: '',
        telephone_number: '',
        delivery_point: '',
        postal_code: '',
        city: '',
        administrative_area: '',
        country: '',
        web_address: '',
        email: 'jonathan.smith@apha.gov.uk',
      },
      '1': {
        tab: 'governance',
        role: 'custodian',
        organization_name: '',
        individual_name: 'Neil Sampson',
        position_name: '',
        telephone_number: '',
        delivery_point: '',
        postal_code: '',
        city: '',
        administrative_area: '',
        country: '',
        web_address: '',
        email: 'neil.sampson@apha.gov.uk',
      },
      '2': {
        tab: 'governance',
        role: 'publisher',
        organization_name: '',
        individual_name: 'APHA OpenData Team',
        position_name: '',
        telephone_number: '',
        delivery_point: '',
        postal_code: '',
        city: '',
        administrative_area: '',
        country: '',
        web_address: '',
        email: 'aphaopendata@apha.gov.uk',
      },
      id: 'c9d7e118-d057-48f9-b520-76de8e51e014',
      title: 'Exotic Notifible Disease Report Case Reason for Submission Vocabulary',
      publishedBy: '',
      startYear: '2008',
      toYear: '2015',
      organisationName: '',
      ncea_group_reference: '',
      project_number: '',
      content: expect.stringContaining(
        'This dataset provides a codelist for the reason why a sample resulting in Non Negative Lab Result was submitted',
      ),
      studyPeriod: '1 January 2008 to 31 December 2015',
      topicCategories: 'environment',
      keywords: 'surveillance, animal disease',
      language: 'ENG',
      host_catalogue_entry: '',
      resource_type_and_hierarchy: '',
      contact_information: 'Peter.Walker@naturalengland.org.uk',
      catalogue_number: '',
      metadata_language: 'ENG',
      publicationInformation: '11 February 2017',
      creationInformation: '10 March 2023',
      revisionInformation: '10 June 2024',
      metadataDate: '',
      lineage: 'An RDF Vocabulary to described data on exotic notifiable disease investigations.',
      limitation_on_public_access: 'otherRestrictions<br>license<br>copyright',
      limitation_on_public_access_otherconstraint: 'Open Government Licence<br>©Crown Copyright, APHA 2016',
      conditions_for_access_and_use_useConstraints: '',
      conditions_for_access_and_useOtherConstraints: '',
      other_constraint: '',
      attribution_statement: '',
      available_formats: '',
      frequency_of_update: 'unknown',
      character_encoding: 'utf8',
      Natural_capital_title: naturalTabStaticData.title,
      Natural_capital_description: naturalTabStaticData.description,
      Natural_capital_displayData: expect.any(String),
      spatialDataService: '',
      spatialRepresentationService: 'vector',
      spatialReferencingSystem: 'http://www.opengis.net/def/crs/EPSG/0/27700',
      geographicLocations: '',
      geographicBoundary: { north: 58.7, south: -50, east: 1.7, west: -6.2 },
      geographicBoundaryHtml:
        '<p>West bounding longitude: <span id="west">-6.2</span></p><p>East bounding longitude: <span id="east">1.7</span></p><p>North bounding latitude: <span id="north">58.7</span></p><p>South bounding latitude: <span id="south">-50</span></p>',
      geographicCenter: '-2.25,4.350000000000001',
      geographicMarkers: '',
      verticalExtent: '',
      samplingResolution: '',
      ncea_catalogue_number: 'c9d7e118-d057-48f9-b520-76de8e51e014',
      resourceWebsite: expect.any(String),
      nceaContribution: '',
      host_catalogue_number: 'c9d7e118-d057-48f9-b520-76de8e51e014',
      child_records: [],
      parent_records: [],
    };
    expect(result).toEqual(expectedResponse);
  });
});
